# Generated by Django 2.2.17 on 2021-01-13 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок картинки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Файл изображения')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('url', models.URLField(verbose_name='ССылка на оригинальную картинку')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_created', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('users_like', models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь поставивший лайк')),
            ],
        ),
    ]
